hydra:
  run:
    dir: .
  output_subdir: null

seed: 1234

logger_level: INFO

path_to_sample: ???
path_to_gt: '/is/cluster/fast/nathanasiou/data/sinc_supmat_gt'
temos_path: "/ps/project/motion_text_synthesis/sinc/experiments/sinc.results/bak_sinc.cvpr_sinc.resume_jz/temos/babel-amass/"

# llocations + z axes + scaling of skeleton
jointstype: 'smplh' # smplh /

# Composing nested config with default
defaults:
  - data: null
  - machine: null
  - trainer: null
  - sampler: all_conseq
  - /path@path
  - override hydra/job_logging: custom
  - override hydra/hydra_logging: custom
  - _self_

data:
  mode: 'inference'

machine:
  batch_size: 16
  smpl_batch_size: 128
