name: spatial_actor_decoder
_target_: sinc.model.motiondecoder.spatial_actor.ActorAgnosticDecoder

latent_dim: ${model.latent_dim}

ff_size: ${model.ff_size}
num_layers: ${model.num_layers}
num_head: ${model.num_head}
droupout: ${model.droupout}
activation: ${model.activation}
njoints: ${model.njoints}
